// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdcgdwsnooapdfejpmbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkY2dkd3Nub29hcGRmZWpwbWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjY3NzQsImV4cCI6MjA2OTQ0Mjc3NH0.eXL2eUQFhfv7Qd2AkPwfdTuZyXyk43_-vfNtQtlTSm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});